#! /bin/bash 

chsh -s $(which zsh)
ln -sf ~/.dotfiles/.zshrc ~/.zshrc
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone git://github.com/yonchu/zsh-vcs-prompt.git ~/.oh-my-zsh/zsh-vcs-prompt


git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -sf ~/.dotfiles/.vimrc ~/.vimrc
vim +PluginInstall +qall

ln -sf ~/.dotfiles/.gitconfig ~/.gitconfig
